### ISSUE TITLE
is there any samples for multy-core?

### ISSUE THREAD

**Issue by MULITICORE** [Multy-io/Multy-Core#9]
hello, I have complied the library of multy-core on ubuntu, and I want to use it as a library for my c++ program which run on linux platform. And my C++ program is used to implement a cold wallet.
I had read the code, but find only one sample of "make_mnemonic" and  "make_seed" in the main.cpp. And in the multy_test, make_dummy_entropy_source is used to make_mnemonic.
Do you have any more samples for using multy-core library, such as "make_hd_account","make_seed","make_mnemonic"
thank you

**Comment by Enmk** [comment]
Hello! Thank you for your question. You can basically use test cases as examples, please see multy_test for details. 
You may want to check out:
```
TEST_P(AccountSmokeTestP, AccountFromEntropy) // for making accounts from mnemonic
GTEST_TEST(BitcoinTransactionTest, SmokeTest_testnet) // for making BTC transaction from certain Account to some address
GTEST_TEST(EthereumTransactionTest, SmokeTest_public_api) // for making ETH transaction from certain Account to some address 
```

In order to build that run cmake with  `-DMULTY_WITH_TESTS:BOOL=ON  -DMULTY_WITH_TEST_APP:BOOL=ON`
